### ISSUE TITLE
current sendfile fetch is racy

### ISSUE THREAD

**Issue by evanmcc** [SpaceTime-IoT/vonnegut#4]
Since logfile reads and writes are happening on different processes, we need to make sure that we aren't sending any partially written results.  Instead of using `filelib:file_size/1`, we should use the index to calculate the correct number of bytes to send.

**Comment by tsloughter** [comment]
Are you positive that the file size would get bumped intermediately during the writing processes flush to disk?

We may also want to look at using some other limiting factor, like a max send config, as well.

**Comment by evanmcc** [comment]
My thought was something like this:

1. logfile stands at 10 messages, all in the same file.
1. fetch request for offset 4 arrives
1. write request for message 11 arrives, it's a large message
1. first chunk of 11 is flushed to files
1. fetch request finds the current file size
1. second chunk of 11 is flushed
1. sendfile sends 4-10 and first chunk of 11
 
Is there something that makes this interleaving impossible?

We should definitely allow max bytes.  I'd like to add offset ranges for fetch, but it doesn't seem to be supported by the protocol.

**Comment by tsloughter** [comment]
That is my question, would a flush of message 11 result in this interleaving, or would the size and file not actually be updated until the whole chunk was written.

**Comment by evanmcc** [comment]
It's probably a per-filesystem thing.  This suggests that anything over 4k is potentially a problem: http://stackoverflow.com/questions/29866047/whats-the-atomic-disk-write-for-a-linux-filesystem

**Comment by tsloughter** [comment]
Ok. Kafka also has a limit on the max message size.

**Comment by evanmcc** [comment]
urgh, complicated config: http://stackoverflow.com/questions/21020347/kafka-sending-a-15mb-message

anyway, that's way bigger than 4k, and I don't imagine a 4k limit on message size is going to make people happy.   also for speed, we're likely going to want to concatenate messages to write them to disk, which could end up breaking them anywhere.

**Comment by tsloughter** [comment]
I wouldn't be surprised if kafka just sends the extra data and the client is expected to drop it.

The only reason to use the size instead of the lookup is speed.

**Comment by evanmcc** [comment]
yeah, dropping it is a valid option, but inefficient for large messages, since you can potentially send and resend the data several times.

**Comment by tsloughter** [comment]
Yea, it is what kafka does. Not that we have to do the same here (we wouldn't even have to consider if we want to break protocol since it would be the same still) but I don't know that doing the lookup is worth it.

**Comment by evanmcc** [comment]
A thought: if we're passing the latest ack'd txid back up the chain (to allow read load to spread out), we could also pass the offset limit back up and keep it handy.

**Comment by tsloughter** [comment]
We'd have to keep it handy in the gen_server (bottleneck) or an ets table (meh).

**Comment by evanmcc** [comment]
Store it in the state for the currently written file, which we have to fetch anyway.

**Comment by tsloughter** [comment]
The index file? We don't read any other file besides with sendfile and that goes straight to the client.

**Comment by evanmcc** [comment]
there was some offline discussion; closing as not really important right now, as the client can always limit its over-read by specifying smaller byte limits, and the read optimization that I mentioned isn't likely to be needed for our usecase.
