### ISSUE TITLE
Cache index

### ISSUE THREAD

**Issue by tsloughter** [SpaceTime-IoT/vonnegut#55]
Currently each lookup in the index requires reading in the index from disk to do the search (even those running in parallel do not share). Caching the read-only index for a topic to share between requests and releasing it after some period of not being accessed would be a better option.

**Comment by evanmcc** [comment]
honestly, I suspect that this won't be worth it.  the linux filesystem block cache is pretty good.

**Comment by tsloughter** [comment]
Yea, I was also thinking it could be indexed better when read into memory to have more efficient look ups. Right now it does a binary search on the flat file. But not something we'll have time for anyway and is a more complicated issue than simply 'caching' which as you say linux already should be doing well for us. So I'll close this but maybe open another in the future about it, but likely not until we actually see index lookup times be problematic I guess.
