### ISSUE TITLE
Design document

### ISSUE THREAD

**Issue by tsloughter** [SpaceTime-IoT/vonnegut#9]
Add a `doc/design.md` document detailing how we plan to implement:

- topic lookup for reads and writes
- replication
- chain assignment (which nodes host what links in a chain)
- chain consensus
- chain monitoring
- guarantees
- configuration

**Comment by evanmcc** [comment]
my proposal for big-table like adaptive topic partitioning: 
https://gist.github.com/evanmcc/e8bfbf2178bb0652ead3b7a452e21dc6

**Comment by evanmcc** [comment]
we should also link or paste the google doc with earlier discussion here.
